apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: file-service:1.0
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: filestorage
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: disable
          # volumeMounts:
          #   - name: file-storage
          #     mountPath: /app/uploads

      # volumes:
      #   - name: file-storage
      #     persistentVolumeClaim:
      #       claimName: file-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file-service
  ports:
    - port: 50051
      targetPort: 50051
  type: NodePort
