name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # ✅ FIX REGION

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 -t file-service:v1 .

      - name: Tag image
        run: |
          docker tag file-service:v1 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/file-service:v1

      - name: Push image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/file-service:v1

      # 🔥 NEW STEP (IMPORTANT)
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-cluster

      # 🔥 NEW STEP (DEPLOY)
      - name: Deploy to Kubernetes PVC
        run: |
          kubectl apply -f k8s/file-pvc.yaml
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/file-service.yaml
